services:
  postgresql:
    container_name: postgresql
    image: postgres:17.5-bullseye
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gloryteam
    networks:
      - glorympia-network
    volumes:
      - ./data/postgresql/gloryteam:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d gloryteam"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  fastapi:
    container_name: fastapi
    build:
      context: ./src/app
    environment:
      - PYTHONPATH=/src
    working_dir: /src/app
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./src/app:/src/app
    ports:
      - "8000:8000"
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - glorympia-network
    restart: always

  glorybot:
    container_name: glorybot
    build:
      context: ./src/glorybot
    environment:
      - PYTHONPATH=/src
    working_dir: /src/glorybot
    command: sh -c "python main.py"
    volumes:
      - ./src/glorybot:/src/glorybot
      - ./sounds:/src/sounds
      - ./configs/.env.glorybot:/src/configs/.env.glorybot
    depends_on:
      - fastapi
    networks:
      - glorympia-network
    restart: always

  test:
    container_name: test
    build:
      context: ./src/app
    working_dir: /
    command: sh -c "pytest tests/app --maxfail=1 --disable-warnings -v"
    environment:
      - PYTHONPATH=/src
    volumes:
      - ./src:/src
      - ./tests:/tests
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - glorympia-network
    restart: "no"

networks:
  glorympia-network:
    driver: bridge