services:
  postgresql:
    container_name: postgresql
    image: postgres:17.5-bullseye
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gloryteam
    networks:
      - olympia-custom-network
    volumes:
      - ./data/postgresql/gloryteam:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d gloryteam"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    profiles:
      - production
      - developer

  fastapi:
    container_name: fastapi
    build:
      context: ./src/app
    environment:
      - PYTHONPATH=/src
    working_dir: /src/app
    entrypoint: /src/app/entrypoint.sh
    volumes:
      - ./src/app:/src/app
      - ./configs/.env.app:/src/configs/.env
    ports:
      - "8000:8000"
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - olympia-custom-network
    restart: always
    profiles:
      - production
      - developer

  agent:
    container_name: agent
    build:
      context: ./src/agent
    environment:
      - PYTHONPATH=/src
    working_dir: /src/agent
    entrypoint: /src/agent/entrypoint.sh
    volumes:
      - ./src/agent:/src/agent
      - ./configs/.env.agent:/src/configs/.env
    ports:
      - "8000:8000"
    networks:
      - olympia-custom-network
    restart: always
    profiles:
      # - production
      - developer

  ocbot:
    container_name: ocbot
    build:
      context: ./src/ocbot
    environment:
      - PYTHONPATH=/src
    working_dir: /src/ocbot
    command: sh -c "python main.py"
    volumes:
      - ./src/ocbot:/src/ocbot
      - ./sounds:/src/sounds
      - ./configs/.env.ocbot:/src/configs/.env
    depends_on:
      - fastapi
    networks:
      - olympia-custom-network
    restart: always
    profiles:
      - production

networks:
  olympia-custom-network:
    driver: bridge